// Auto-generated by fix-dates.js
// Last run: 2025-08-15T00:19:59.913Z

export const CURRENT_DATE = '2025-08-15';
export const CURRENT_YEAR = 2025;
export const CURRENT_MONTH = '08';
export const LAST_BUILD = '2025-08-15T00:19:59.913Z';

// Dynamic helpers (always current)
export const getDynamicDate = () => new Date().toISOString().split('T')[0];
export const getDynamicYear = () => new Date().getFullYear();
export const getDynamicTimestamp = () => new Date().toISOString();

// Copyright
export const COPYRIGHT = `© ${getDynamicYear()} Meterr.ai. All rights reserved.`;
