version: '3.8'
services:
  gateway:
    build: .
    ports:
      - "8080:8080"
    environment:
      - METERR_KEY=${METERR_KEY}
      - DATABASE_URL=postgres://db:5432/meterr
    volumes:
      - ./data:/app/data
  
  dashboard:
    image: meterr/dashboard:latest
    ports:
      - "3000:3000"
    depends_on:
      - gateway
  
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: meterr
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: