version: '3.8'

services:
  langfuse:
    image: langfuse/langfuse:latest
    container_name: meterr-langfuse
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://langfuse:langfuse123@langfuse-db:5432/langfuse
      - NEXTAUTH_URL=http://localhost:3002
      - NEXTAUTH_SECRET=your-secret-key-change-in-production
      - SALT=your-salt-change-in-production
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=true
    depends_on:
      - langfuse-db
    networks:
      - langfuse-network

  langfuse-db:
    image: postgres:15
    container_name: meterr-langfuse-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse123
      POSTGRES_DB: langfuse
    volumes:
      - langfuse_postgres_data:/var/lib/postgresql/data
    networks:
      - langfuse-network

volumes:
  langfuse_postgres_data:

networks:
  langfuse-network:
    driver: bridge