import type * as Preset from '@docusaurus/preset-classic';
import type { Config } from '@docusaurus/types';
import { themes as prismThemes } from 'prism-react-renderer';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const config: Config = {
  title: 'Meterr Documentation',
  tagline: 'Save up to 30% on AI Costs - Track, Optimize, Scale',
  favicon: 'img/favicon.ico',

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  // Set the production url of your site here
  url: 'https://docs.meterr.ai',
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: '/',

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: 'lfriedbauer', // Usually your GitHub org/user name.
  projectName: 'meterr', // Usually your repo name.

  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',

  // Internationalization configuration for multi-language support
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'es', 'fr', 'de', 'ja', 'zh'],
    localeConfigs: {
      en: {
        label: 'English',
        direction: 'ltr',
        htmlLang: 'en-US',
        calendar: 'gregory',
        path: 'en',
      },
      es: {
        label: 'Español',
        direction: 'ltr',
        htmlLang: 'es-ES',
        calendar: 'gregory',
        path: 'es',
      },
      fr: {
        label: 'Français',
        direction: 'ltr',
        htmlLang: 'fr-FR',
        calendar: 'gregory',
        path: 'fr',
      },
      de: {
        label: 'Deutsch',
        direction: 'ltr',
        htmlLang: 'de-DE',
        calendar: 'gregory',
        path: 'de',
      },
      ja: {
        label: '日本語',
        direction: 'ltr',
        htmlLang: 'ja-JP',
        calendar: 'gregory',
        path: 'ja',
      },
      zh: {
        label: '中文',
        direction: 'ltr',
        htmlLang: 'zh-CN',
        calendar: 'gregory',
        path: 'zh',
      },
    },
  },

  plugins: [
    // CodeSandbox embed plugin for interactive tutorials
    [
      '@docusaurus/plugin-ideal-image',
      {
        quality: 85,
        max: 1920,
        min: 640,
        steps: 3,
        disableInDev: false,
      },
    ],
    // Local search plugin
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        hashed: true,
        language: ['en', 'es', 'fr', 'de', 'ja', 'zh'],
        indexDocs: true,
        indexBlog: false,
        indexPages: true,
        docsRouteBasePath: '/docs',
        searchBarPosition: 'right',
        searchBarShortcutHint: true,
      },
    ],
    // Google Analytics
    [
      '@docusaurus/plugin-google-gtag',
      {
        trackingID: 'G-XXXXXXXXXX', // Replace with actual GA4 tracking ID
        anonymizeIP: true,
      },
    ],
    // OpenAPI Documentation Plugin for multi-provider support
    [
      'docusaurus-plugin-openapi-docs',
      {
        id: 'openapi',
        docsPluginId: 'classic',
        config: {
          meterr_api: {
            specPath: 'openapi/meterr-api.yaml',
            outputDir: 'docs/api/reference',
            sidebarOptions: {
              groupPathsBy: 'tag',
              categoryLinkSource: 'tag',
            },
            template: 'api.mustache',
            showSchemas: true,
          },
          provider_proxies: {
            specPath: 'openapi/provider-proxies.yaml',
            outputDir: 'docs/api/providers',
            sidebarOptions: {
              groupPathsBy: 'provider',
            },
          },
        },
      },
    ],
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          // Performance optimizations
          showLastUpdateTime: true,
          showLastUpdateAuthor: true,
          remarkPlugins: [[require('@docusaurus/remark-plugin-npm2yarn'), { sync: true }]],
          // Enable versioning for roadmap phases
          versions: {
            current: {
              label: 'v3.0 (Scale)',
              path: 'scale',
              badge: true,
            },
            '2.0': {
              label: 'v2.0 (Growth)',
              path: 'growth',
            },
            '1.0': {
              label: 'v1.0 (MVP)',
              path: 'mvp',
            },
          },
          lastVersion: 'current',
          // Auto-generate sidebars for better organization
          sidebarCollapsible: true,
          sidebarCollapsed: false,
          // Enable autogenerated sidebars
          sidebarItemsGenerator: async ({ defaultSidebarItemsGenerator, ...args }) => {
            const sidebarItems = await defaultSidebarItemsGenerator(args);
            // Auto-include ARCHITECTURE.md and technical docs
            return sidebarItems;
          },
          // Breadcrumbs for better navigation
          breadcrumbs: true,
          // Show last update time and author
          showLastUpdateTime: true,
          showLastUpdateAuthor: true,
          // Edit URL for GitHub
          editUrl: 'https://github.com/lfriedbauer/meterr/tree/main/docs-portal/',
          // Include MDX support for advanced documentation
          remarkPlugins: [],
          rehypePlugins: [],
          // Route base path
          routeBasePath: 'docs',
          // Additional metadata for docs
          docItemComponent: '@theme/DocItem',
        },
        blog: {
          showReadingTime: true,
          feedOptions: {
            type: ['rss', 'atom'],
            xslt: true,
          },
          editUrl: 'https://github.com/lfriedbauer/meterr/tree/main/docs-portal/',
          // Useful options to enforce blogging best practices
          onInlineTags: 'warn',
          onInlineAuthors: 'warn',
          onUntruncatedBlogPosts: 'warn',
          blogTitle: 'Meterr Blog',
          blogDescription: 'Latest updates on AI cost optimization and platform features',
          postsPerPage: 10,
          blogSidebarTitle: 'Recent posts',
          blogSidebarCount: 5,
        },
        theme: {
          customCss: './src/css/custom.css',
        },
        sitemap: {
          changefreq: 'weekly',
          priority: 0.5,
          ignorePatterns: ['/tags/**'],
          filename: 'sitemap.xml',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // Social card for sharing
    image: 'img/meterr-social-card.jpg',
    // SEO metadata
    metadata: [
      {
        name: 'keywords',
        content:
          'AI cost tracking, LLM expense management, OpenAI costs, Anthropic billing, AI optimization, token tracking',
      },
      {
        name: 'description',
        content:
          'Meterr helps teams save up to 30% on AI costs. Track usage across OpenAI, Anthropic, Google AI. Real-time monitoring, budget alerts, and optimization insights.',
      },
      {
        name: 'og:description',
        content:
          'Save up to 30% on AI costs with Meterr. Track, optimize, and manage expenses across all major AI providers.',
      },
      { name: 'twitter:card', content: 'summary_large_image' },
      { name: 'twitter:creator', content: '@meterr_ai' },
      { name: 'og:type', content: 'website' },
    ],
    // Announcement bar for important updates
    announcementBar: {
      id: 'support_us',
      content:
        '🚀 Meterr is now in MVP! Save up to 30% on your AI costs. <a target="_blank" rel="noopener noreferrer" href="https://meterr.ai">Get Started</a>',
      backgroundColor: '#4F46E5',
      textColor: '#ffffff',
      isCloseable: true,
    },
    algolia: {
      appId: 'FPTRIXA309',
      apiKey: '9549344cd69fa39375579ccf6999ff12',
      indexName: 'meterr-docs',
      contextualSearch: true,
      searchPagePath: 'search',
      // Enhanced search configuration for API reference
      searchParameters: {
        facetFilters: ['language:en', 'docusaurus_tag:docs-default-current'],
        attributesToRetrieve: ['hierarchy', 'content', 'anchor', 'url', 'type'],
        attributesToHighlight: ['hierarchy', 'content'],
        attributesToSnippet: ['content:20'],
      },
      // Index API endpoints and code examples
      replaceSearchResultPathname: {
        from: '/docs/',
        to: '/',
      },
      insights: true,
      debug: false,
    },
    navbar: {
      title: 'Meterr',
      logo: {
        alt: 'Meterr Logo',
        src: 'img/logo.svg',
        srcDark: 'img/logo-dark.svg',
      },
      hideOnScroll: false,
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docsSidebar',
          position: 'left',
          label: 'Documentation',
        },
        {
          type: 'doc',
          docId: 'architecture',
          position: 'left',
          label: 'Architecture',
        },
        {
          type: 'doc',
          docId: 'api/overview',
          position: 'left',
          label: 'API',
        },
        { to: '/blog', label: 'Blog', position: 'left' },
        {
          type: 'docsVersionDropdown',
          position: 'right',
          dropdownActiveClassDisabled: true,
        },
        {
          href: 'https://github.com/lfriedbauer/meterr',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Documentation',
          items: [
            {
              label: 'Getting Started',
              to: '/docs/intro',
            },
            {
              label: 'Architecture',
              to: '/docs/architecture',
            },
            {
              label: 'API Reference',
              to: '/docs/api/overview',
            },
            {
              label: 'Roadmap',
              to: '/docs/roadmap',
            },
          ],
        },
        {
          title: 'Community',
          items: [
            {
              label: 'Discord',
              href: 'https://discord.gg/meterr',
            },
            {
              label: 'Twitter',
              href: 'https://twitter.com/meterr_ai',
            },
            {
              label: 'LinkedIn',
              href: 'https://linkedin.com/company/meterr',
            },
            {
              label: 'Product Hunt',
              href: 'https://producthunt.com/products/meterr',
            },
          ],
        },
        {
          title: 'Resources',
          items: [
            {
              label: 'Blog',
              to: '/blog',
            },
            {
              label: 'Pricing Calculator',
              href: 'https://meterr.ai/calculator',
            },
            {
              label: 'Status Page',
              href: 'https://status.meterr.ai',
            },
            {
              label: 'Support',
              href: 'https://support.meterr.ai',
            },
          ],
        },
        {
          title: 'Company',
          items: [
            {
              label: 'About',
              href: 'https://meterr.ai/about',
            },
            {
              label: 'GitHub',
              href: 'https://github.com/lfriedbauer/meterr',
            },
            {
              label: 'Privacy Policy',
              href: 'https://meterr.ai/privacy',
            },
            {
              label: 'Terms of Service',
              href: 'https://meterr.ai/terms',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Meterr.ai - Save up to 30% on AI Costs | Built with Docusaurus`,
      logo: {
        alt: 'Meterr Logo',
        src: 'img/logo.svg',
        href: 'https://meterr.ai',
        width: 160,
        height: 51,
      },
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['python', 'java', 'ruby', 'go', 'rust'],
    },
    // Performance optimizations
    colorMode: {
      defaultMode: 'light',
      disableSwitch: false,
      respectPrefersColorScheme: true,
    },
    // Language switcher in navbar
    navbar: {
      items: [
        // ... existing items ...
        {
          type: 'localeDropdown',
          position: 'right',
          dropdownItemsAfter: [
            {
              type: 'html',
              value: '<hr style="margin: 0.3rem 0;">',
            },
            {
              href: 'https://github.com/lfriedbauer/meterr/issues',
              label: 'Help translate',
            },
          ],
        },
      ],
    },
  } satisfies Preset.ThemeConfig,
  // Performance and build optimizations
  webpack: {
    jsLoader: (isServer) => ({
      loader: require.resolve('swc-loader'),
      options: {
        jsc: {
          parser: {
            syntax: 'typescript',
            tsx: true,
          },
          transform: {
            react: {
              runtime: 'automatic',
            },
          },
        },
      },
    }),
  },
  // Enable faster builds
  faster: true,
};

export default config;
