import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Meterr Documentation Sidebars
 * Organized by user journey and technical depth
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  docsSidebar: [
    'intro',
    'architecture',
    'roadmap',
    {
      type: 'category',
      label: 'Architecture',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'architecture'},
      ],
    },
    {
      type: 'category',
      label: 'API',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'api'},
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'deployment'},
      ],
    },
    {
      type: 'category',
      label: 'Security',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'security'},
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'contributing'},
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'integrations'},
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'tutorial-basics'},
        {type: 'autogenerated', dirName: 'tutorial-extras'},
      ],
    },
  ],

  // API-specific sidebar
  apiSidebar: [
    {type: 'autogenerated', dirName: 'api'},
  ],

  // Tutorial sidebar
  tutorialSidebar: [
    {type: 'autogenerated', dirName: 'tutorial-basics'},
    {type: 'autogenerated', dirName: 'tutorial-extras'},
  ],
};

export default sidebars;