import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Meterr Documentation Sidebars
 * Organized by user journey and technical depth
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar - organized by user journey
  docsSidebar: [
    {
      type: 'category',
      label: '🚀 Getting Started',
      collapsed: false,
      items: [
        'intro',
        { type: 'autogenerated', dirName: 'getting-started' },
        { type: 'autogenerated', dirName: 'tutorial-basics' },
      ],
    },
    {
      type: 'category',
      label: '💡 Core Features',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'features' },
        {
          type: 'category',
          label: 'Integrations',
          items: [{ type: 'autogenerated', dirName: 'integrations' }],
        },
      ],
    },
    {
      type: 'category',
      label: '🔧 Advanced Features',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'API Reference',
          items: [{ type: 'autogenerated', dirName: 'api' }],
        },
        { type: 'autogenerated', dirName: 'tutorial-extras' },
        {
          type: 'category',
          label: 'Webhooks & Automation',
          items: [{ type: 'autogenerated', dirName: 'api/webhooks' }],
        },
      ],
    },
    {
      type: 'category',
      label: '🏗️ Architecture & Infrastructure',
      collapsed: true,
      items: [
        'architecture',
        { type: 'autogenerated', dirName: 'architecture' },
        {
          type: 'category',
          label: 'Deployment',
          items: [{ type: 'autogenerated', dirName: 'deployment' }],
        },
      ],
    },
    {
      type: 'category',
      label: '🔒 Security & Compliance',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'security' }],
    },
    {
      type: 'category',
      label: '📋 Resources',
      collapsed: true,
      items: [
        'roadmap',
        { type: 'autogenerated', dirName: 'resources' },
        {
          type: 'category',
          label: 'Contributing',
          items: [{ type: 'autogenerated', dirName: 'contributing' }],
        },
      ],
    },
  ],

  // API-specific sidebar
  apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],

  // Tutorial sidebar
  tutorialSidebar: [
    { type: 'autogenerated', dirName: 'tutorial-basics' },
    { type: 'autogenerated', dirName: 'tutorial-extras' },
  ],
};

export default sidebars;
